FROM python:3.10

WORKDIR /app

ENV VIRTUAL_ENV=/app/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY docker-containers/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 80

ENV FASTAPI_ENV production

CMD ["/app/venv/bin/python", "./venv/bin/uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]

